apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  ALGORITHM: {{ .Values.env.ALGORITHM | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.env.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}
  LOCK_TTL_SECONDS: {{ .Values.env.LOCK_TTL_SECONDS | quote }}
  CORS_ORIGINS: {{ .Values.env.CORS_ORIGINS | quote }}
